# Generated by Django 3.2.7 on 2021-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGrade',
            fields=[
                ('book_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_grade', models.IntegerField()),
            ],
            options={
                'db_table': 'Book_Grade',
                'managed': False,
            },
        ),
    ]
