# Generated by Django 3.2.7 on 2021-10-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBasedCFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ItemBasedCFModel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserBasedCFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserBasedCFModel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPredictedGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'UserPredictedGradeModel',
                'managed': False,
            },
        ),
    ]
