# Generated by Django 3.2.7 on 2021-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_itembasedcfmodel_userpredictedgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPredictedGradeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('book_isbn', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'UserPredictedGradeModel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserPredictedGrade',
        ),
    ]
