# Generated by Django 3.2.7 on 2021-10-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_bestbookten'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestBookTenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'BestBookTenModel',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BestBookTen',
        ),
    ]
