# Generated by Django 3.2.7 on 2021-09-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_isbn', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('book_title', models.TextField()),
                ('book_author', models.TextField()),
                ('book_pub', models.TextField()),
                ('book_pub_date', models.CharField(max_length=10)),
                ('book_add_code', models.CharField(max_length=5)),
                ('book_price', models.IntegerField()),
                ('book_img_url', models.TextField()),
                ('book_desc', models.TextField()),
                ('book_kdc', models.CharField(max_length=20)),
                ('book_category_code', models.CharField(max_length=5)),
                ('book_keyword1', models.CharField(max_length=100)),
                ('book_keyword2', models.CharField(max_length=100)),
                ('book_keyword3', models.CharField(max_length=100)),
            ],
        ),
    ]
