# Generated by Django 3.2.7 on 2021-09-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
