# Generated by Django 3.2.7 on 2021-09-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_add_code',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_kdc',
        ),
    ]
