# Generated by Django 3.2.7 on 2021-09-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('user_nickname', models.CharField(max_length=100)),
                ('user_profile_url', models.CharField(blank=True, max_length=200, null=True)),
                ('user_join_type', models.IntegerField()),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
